# Generated by Django 4.2.8 on 2026-08-03 06:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycheckin',
            name='responses',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='dailycheckin',
            name='energy_level',
            field=models.CharField(blank=True, choices=[('very_low', 'Very Low'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='dailycheckin',
            name='mood',
            field=models.CharField(blank=True, choices=[('very_bad', 'Very Bad'), ('bad', 'Bad'), ('neutral', 'Neutral'), ('good', 'Good'), ('very_good', 'Very Good')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='dailycheckin',
            name='sleep_hours',
            field=models.FloatField(blank=True, help_text='Hours of sleep', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
