# Generated by Django 4.2.8 on 2026-08-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='chest',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hip',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='transition_direction',
            field=models.CharField(blank=True, choices=[('feminizing', 'Feminizing'), ('masculinizing', 'Masculinizing')], help_text='Direction used by the transition timeline visualization', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='waist',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
